### PR TITLE
support for Node.js 12

### PR DESCRIPTION
**Pull request by Xmader**

### CODE REVIEW

**Comment by alanshaw** [comment]
Please can has merge and release 🙏

**Comment by okdistribute** [comment]
okay i'll do a major bump

**Comment by okdistribute** [comment]
thanks so much @Xmader and @alanshaw ! keepin things rollin!

**Comment by alanshaw** [comment]
thanks @karissa - it doesn't seem to be published on npm yet though?

**Comment by alanshaw** [comment]
ping @karissa - can you publish please?

**Comment by okdistribute** [comment]
@alanshaw okay it is published now, sorry for the delay.

**Pull request merged**
